name: gateway_build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ nasa-gateway ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    #strategy:
    #  fail-fast: false
    #  matrix:
    #    python-version: ["3.8"]
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: build and push docker image
      id: docker-build
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: ksusau/gateway
        tags: latest,${{ github.sha }}
        registry: docker.io
        dockerfile: Dockerfile
        username: kausau
        password: 36706a13-98ab-4363-800f-fbd9415216d6
    - name: Make a push for CD
      run: |
        git config --local user.email "kumarsaurabh737@gmail.com"
        git config --local user.name "Github action"
        git checkout cd
        sed -i -r "s/kausau.*/kausau\/gateway:${{ github.sha }}/" gateway/k8/gateway-deployment.yml
        git commit -a --allow-empty -m "Update image for deployment" 
        git push origin cd
